version: '3'
services:
  db:
    container_name: skeleton-db
    image: postgres:12.6-alpine
    environment:
      - POSTGRES_DB=skeleton
      - DATABASE_HOST=database
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - skeleton-data:/var/lib/postgresql/data
    networks:
      skeleton:
        aliases:
          - database
  migrate:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    volumes:
       - ./deploy/migrations:/migrate/migrations
    command: ["-path", "/migrate/migrations", "-database",  "postgres://postgres:@database:5432/skeleton?sslmode=disable", "up"]
    depends_on:
      - db
    networks:
      - skeleton
  app:
    container_name: skeleton-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      skeleton:

networks:
  skeleton:

volumes:
    skeleton-data: